### ISSUE TITLE
avoid init() functions

### ISSUE THREAD

**Issue by j0hnsmith** [f-secure-foundry/tamago#10]
From the readme

>Go applications are simply required to import, the relevant board package to ensure that hardware initialization >and runtime support takes place:
>
>```
>import (
>	// Example for USB armory Mk II
>	_ "github.com/f-secure-foundry/tamago/board/f-secure/usbarmory/mark-two"
>)
>```

Underscore imports to trigger `init()` functions is discouraged, is it too late to change to 

```
import (
    "github.com/f-secure-foundry/tamago/board/f-secure/usbarmory/mark-two"
)

func main() {
    marktwo.Init()
}
```

**Comment by abarisani** [comment]
The import is required to have a [function linked and made available for runtime](https://github.com/f-secure-foundry/tamago/blob/master/board/f-secure/usbarmory/mark-two/usbarmory.go#L35).

This must be done before main() gets a chance to execute.
