### ISSUE TITLE
UART initialization

### ISSUE THREAD

**Issue by saper** [f-secure-foundry/tamago#29]
I was reading the UART code and I have few questions:

1. Clock frequency: Page 630 of IMX6ULLRM seems to suggest that only `PLL3_FREQ` gets divided by 6; if running on oscillator frequency this should not be done, but https://github.com/f-secure-foundry/tamago/blob/60c33cfb0e60b29dda937a35cd11acd7a44acd42/soc/imx6/uart.go#L281 does it for both cases.
2. p.3603 suggests one should wait for UTS bit 0 to become 0 to wait for the reset to complete.  https://github.com/f-secure-foundry/tamago/blob/60c33cfb0e60b29dda937a35cd11acd7a44acd42/soc/imx6/uart.go#L234 waits on UCR2 bit 0 instead. Is this better for some reason?

3. https://github.com/f-secure-foundry/tamago/blob/60c33cfb0e60b29dda937a35cd11acd7a44acd42/soc/imx6/uart.go#L332-L338 waits for Tx FIFO to be empty after every character. Wouldn't that be better to wait before sending only if Tx FIFO gets full?

(I can't run it yet due to build issue https://github.com/f-secure-foundry/tamago-example/issues/8 )

**Comment by andrejro** [comment]
Points 1. and 3. should be fixed in #30.
Regarding point 2: checking UCR2_SRST should be equivalent to checking UTS[0]. In fact on pg 3639 of the IMX6ULLRM the UTS[0] description includes: "Indicates the status of the software reset (SRST_B of UCR2)".
