### ISSUE TITLE
Raspberry Pi Zero support?

### ISSUE THREAD

**Issue by korpa** [f-secure-foundry/tamago#3]
Do you have a timeline for Raspberry Pi Zero Support?

**Comment by andrejro** [comment]
We aim to have an initial support in May.

**Comment by korpa** [comment]
Hi @andrejro,

any news on this?

**Comment by abarisani** [comment]
Things got delayed, it's ready when it's ready. We won't commit to a specific timeline at this point, please track the project for updates. Thanks!

**Comment by abarisani** [comment]
FYI: https://github.com/f-secure-foundry/tamago/tree/master/board/raspberrypi

**Comment by korpa** [comment]
Yippie. Thank you very much.
