### ISSUE TITLE
Raspberry Pi use and the need for U-boot

### ISSUE THREAD

**Issue by prusnak** [f-secure-foundry/tamago#8]
Section `Executing and debugging` of https://github.com/f-secure-foundry/tamago/blob/master/board/raspberrypi/README.md mentioned U-Boot, but it seems that both examples ([Pi Zero](https://github.com/kenbell/tamago-example-pizero) and [Pi 2](https://github.com/kenbell/tamago-example-pi2)) got rid of the U-boot recently.

Can you please clarify the situation and if the U-Boot is really no longer needed update the README.md to not mention it?

**Comment by abarisani** [comment]
@kenbell can you comment?

**Comment by kenbell** [comment]
Oh yeah - we should update README.  I'll work on an update.

You can either follow the docs and do U-boot, or do as the examples and prepend a stub to the binaries to emulate the linux kernel to the Pi firmware.  Either should work.  Avoiding U-boot is a bit quicker to load.

**Comment by bburky** [comment]
Please expand the README to include what files are needed from "an existing Raspberry Pi bootable SD card (note critical Pi firmware is loaded from the SDcard, so blank cards cannot be used)." That just refers to needing an existing `/boot` partition, right?

**Comment by kenbell** [comment]
@bburky - yes in raspbian, it's /boot, on the micro-sd card itself it's the files in the root directory.

**Comment by abarisani** [comment]
This should be fixed now that https://github.com/f-secure-foundry/tamago/pull/11 has been merged, if there are more concerns please re-open.

Thanks!
