### ISSUE TITLE
Clarification on multi-core utilization

### ISSUE THREAD

**Issue by gurre** [f-secure-foundry/tamago#9]
Could you please clarify how any Go application would utilize the CPU cores on the device? E.g. will it run using only one core?

On another topic, given that the CPU directly executes the Go program code without an intermediate(?), does that give you true real-time execution?

**Comment by abarisani** [comment]
For now there is no multi-core support in TamaGo, so everything is executed on a single core (the supported i.MX6 targets and the Pi Zero are single-core anyway).

Yes, there is real-time execution of the Go runtime, not the final Go program code though (as the runtime performs GC while your app is running).
